background #000000
foreground #ffffff

cursor #ffffff

selection_foreground #ffffff
selection_background #444444

color0  #000000
color1  #ff8080
color2  #80ffaa
color3  #d8d877
color4  #88bbff
color5  #bf99ee
color6  #00bfff
color7  #ffffff
color8  #bbbbbb
color9  #ff5555
color10 #55ff55
color11 #ffff55
color12 #5555ff
color13 #ff55ff
color14 #33dfff
color15 #ffffff

# Color palette table:
# | KITTY NAME | COLOR         | HEX CODE |
# |------------|---------------|----------|
# | color0     | black         | 000000   |
# | color1     | red           | ff8080   |
# | color2     | green         | 80ffaa   |
# | color3     | yellow        | d8d877   |
# | color4     | blue          | 88bbff   |
# | color5     | purple        | bf99ee   |
# | color6     | cyan          | 00bfff   |
# | color7     | white         | ffffff   |
# | color8     | grey          | bbbbbb   |
# | color9     | bright-red    | ff5555   |
# | color10    | bright-green  | 55ff55   |
# | color11    | bright-yellow | ffff55   |
# | color12    | bright-purple | 5555ff   |
# | color13    | bright-pink   | ff55ff   |
# | color14    | bright-cyan   | 33dfff   |
# | color15    | bright-white  | ffffff   |
#
# Unoffcial colors (not in kitty theme)
# | turquoise | 049595 |
# | orange    | ff9900
# |

