
conky.config = {
    xinerama_head = 1,             -- monitor
    alignment = 'bottom_left',     -- screen alignment
    gap_x = 10,                    -- gap between screen border on x axis
    gap_y = 10,                    -- gap between screen border on y axis
    background = true,            -- ????
    own_window = true,             -- allows transparency
    own_window_type = 'override',  -- draws window on desktop 
    own_window_transparent = false,    -- makes background transparent 
    double_buffer = true,          -- allows for smooth rendering
    draw_shades = false,           -- drop shadow behind window
    minimum_width = 200,           -- minimum width of window
    minimum_height = 50,           -- minimum hight of window
    use_xft = true,                -- enables support for TrueType fonts
    font = 'CaskaydiaMono NF:size=10', -- font and font size
    own_window_argb_value = 128,
    own_window_argb_visual = true,
    own_window_colour = '#000000',
};

--[[
conky.config = {
    -- window
    xinerama_head = 1, 
    alignment = 'bottom_left',
    gap_x = 0,
    gap_y = 0,
    minimum_height = 300,
    minimum_width = 460,
    maximum_width = 460,
    background = false,
    border_width = 0,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    -- Colors
    font = 'CaskaydiaMono NF:size=10', -- font and font size
    font1 = 'RobotoMono Nerd Font:size=11',
    color1 = '#f3f3f3',                        -- accent
    color2 = '#c8c8c8',                        -- accent dimmed
    own_window_transparent = false,            -- transparency
    own_window_argb_visual = true,             -- transparency
    own_window_argb_value = 50,               -- transparency [0 -255]
    own_window_colour = '#121214',             -- bg color [comment to full transparency]
    default_color = 'white',                   -- default colors
    default_outline_color = 'white',           -- default colors
    default_shade_color = 'white',             -- default colors
    double_buffer = true,                      -- removes flickering
    draw_borders = false,                      -- borders (window)
    draw_graph_borders = true,                 -- borders (graphs)
    draw_outline = false,                      -- border (text)
    draw_shades = false,                       -- shades
    extra_newline = false,                     -- extra newline at the end when writing to stdout
    -- other
    update_interval = 1.0,
    cpu_avg_samples = 4,
    net_avg_samples = 4,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}
--]]
conky.text = [[
${execi 5 bash -c "$HOME/.config/conky/todo.sh"}
]];

