# Configuration:
# format: <expression1>, <expression2> ... = <execution>

# Expressions:
# mime | mime type of file (regex)
# ext  | extension of file (regex)
# X    | if the session is graphical

# Used Variables:
# BROWSER         = graphical browser
# EDITOR          = text editor
# AUDIO_PLAYER    = audio player
# VIDEO_PLAYER    = graphical video player
# IMAGE_EDITOR    = graphical image editor
# VECTOR_EDITOR   = graphical vector editor
# DOCUMENT_EDITOR = graphical document editor

# website files (html)
ext x?html?, X, flag f = "${BROWSER}" -- "$@"

# any text (txt, css, c)
mime ^text = "${EDITOR}" -- "$@"

# manpages (1)
ext 1 = man "$1"

# audio (mp3, ogg)
mime ^audio,    flag f = "${AUDIO_PLAYER}" -- "$@"
# video (mp4, mov)
mime ^video, X, flag f = "${VIDEO_PLAYER}" -- "$@"

# .pdf
ext pdf, X, flag f = "${BROWSER}" -- "$@"

# documents (doc, ppt)
ext pptx?|od[dfgpst]|docx?|sxc|xlsx?|xlt|xlw|gnm|gnumeric, X, flag f = "${DOCUMENT_EDITOR}" "$@"

# vector images (svg)
mime ^image/svg, X, flag f = "${VECTOR_EDITOR}" -- "$@"

# images (png, jpg, gif)
mime ^image, X, flag f = "${IMAGE_EDITOR}" -- "$@"

# gimp save files (xcf)
ext xcf, X, flag f = gimp -- "$@"

# ask for anything not specified (this line should always be at the bottom)
 = ask
