qtile folder .config/qtile/
picom folder .config/picom/
kitty folder .config/kitty/
ranger folder .config/ranger/
rofi folder .config/rofi/
nvim folder .config/nvim/
dunst folder .config/dunst/
conky folder .config/conky/
firefox folder .mozilla/firefox/
bashrc file .bashrc
xinitrc file .xinitrc
xprofile file .xprofile
bash_env file .bash_env
.local/bin folder .local/bin/
configs file .config/config_files.conf

