.dotfiles folder ./
dwm folder .compiled/dwm/
st folder .compiled/st/
dmenu folder .compiled/dmenu/
ranger folder .config/ranger/
nvim folder .config/nvim/
firefox folder .mozilla/firefox/
bashrc file .bashrc
xinitrc file .xinitrc
bash_env file .bash_env
bin folder .local/bin/
configs file .config/config_files.conf
duttsy-ignore file .duttsy-ignore
slock folder .compiled/slock/
